LNKFLAGS = 

DIREXE = exec/
DIRHEA = include/
DIRSRC = src/

NEXEC1 = DaenerysTryp


all : $(NEXEC1) $(NEXEC2) $(NEXEC3)

$(NEXEC1) : $(DIRSRC)Daenerys.c $(DIRHEA)orders.h
	gcc $(LNKFLAGS) -I $(DIRHEA) -o $(DIREXE)$(NEXEC1) $(DIRSRC)Daenerys.c


